### ISSUE TITLE
i cannot create folder,Could not dispatch event: class ir.cafebazaar.notepad.events.FolderCreatedEvent to subscribing class class ir.cafebazaar.notepad.activities.addtofolders.Adapter

### ISSUE THREAD

**Issue by buyaonitongle** [MohMah/android-notepad#7]
06-01 03:21:49.074 19570-19570/ir.cafebazaar.notepad_test E/EventBus: Could not dispatch event: class ir.cafebazaar.notepad.events.FolderCreatedEvent to subscribing class class ir.cafebazaar.notepad.activities.addtofolders.Adapter
    java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at ir.cafebazaar.notepad.activities.addtofolders.Adapter.onFolderCreatedEvent(Adapter.java:92)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
        at ir.cafebazaar.notepad.activities.editfolders.NewFolderViewHolder.add(NewFolderViewHolder.java:108)
        at ir.cafebazaar.notepad.activities.editfolders.NewFolderViewHolder.access$000(NewFolderViewHolder.java:27)
        at ir.cafebazaar.notepad.activities.editfolders.NewFolderViewHolder$2.onEditorAction(NewFolderViewHolder.java:47)
        at android.widget.TextView.onEditorAction(TextView.java:6265)
        at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
06-01 03:21:49.074 19570-19570/ir.cafebazaar.notepad_test D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent

**Comment by dhruvanbhalara** [comment]
any solution you found?

**Comment by MohMah** [comment]
It's been fixed
